# Test your FastAPI endpoints

GET http://127.0.0.1:8000/api/v1/jobs
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InZHbENva05kNXktUTA4dzNPZnVBViJ9.eyJlbWFpbCI6ImRhbmllbEBnbWFpbC5jb20iLCJpc3MiOiJodHRwczovL2Rldi1mbzBtN2drZWhhemF5Z3BlLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw2NjEyOTljZmEwMDlkYmI3YjkwZWZmOTMiLCJhdWQiOlsiYXNrdGhlc2hlbGYuY29tIiwiaHR0cHM6Ly9kZXYtZm8wbTdna2VoYXpheWdwZS51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzEyNTM1NzIwLCJleHAiOjE3MTI1NDI5MjAsInNjb3BlIjoib3BlbmlkIGVtYWlsIiwiYXpwIjoiZnIxYVdmSElsZGxWaFFmSlJLQWtTTFQ5eWdwRkVNa3AifQ.SPari30KKHIQUSrL94jVTJcocZINRbqnyai86tTVUdcyiUZsPMqrDfkWCyjxN0aQzuo5h9LDU_jkfJVcCo1kw-oHhx-rZYfH-1XvtmMdQMlPrhB1Ejof4Gf4J_klZjR0mY1-XxhQYaP7hg5Q7QHzp66Dgg_yOadITvpGdT9n4ACWrNEeq0EcvstYLNo2htIUOaUnLCdfVjzHdKLVQ65ORnef_OLLAb4UZNV_sf8jok4yStNEDckPC5NAzOLZ4nOwhm7godCW7JGXwmEbJBSzXHaBG_6VULtrKoV3eUfmOwCc7hk6qhKp-VH-ucvPwEscwR0_TIhr9tneImJSXztNvQ

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###
